name: UWTB
author: Matt Bierner
description: "Sending things to Earth... Bits... Html... Rainbows..."
url: https://blog.mattbierner.com
paginate: 10

google_analytics: UA-69534023-1


baseurl: ""

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

permalink: /:title/

future: true

feed:
  path: atom.xml

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - support
